.PHONY: all install build

all: build
	@echo "Run 'make install' to install occlib to system path"

install: build
	python setup.py install

build:
	python setup.py build

clean:
	@echo "Nothing to be done for clean"
